import logging
from datetime import datetime
from typing import Any, Dict, Optional

import httpx

from ..core.config import settings
from ..models.pipeline import PipelineEntry

log = logging.getLogger(__name__)


def _to_date_only(value: Optional[str]) -> Optional[str]:
    if not value:
        return None
    try:
        return datetime.fromisoformat(value).date().isoformat()
    except ValueError:
        # If it already looks like YYYY-MM-DD, return as-is; otherwise, skip it
        trimmed = value.strip()
        if len(trimmed) >= 10 and trimmed[4] == "-" and trimmed[7] == "-":
            return trimmed[:10]
        return None


def _extract_digits(value: Optional[str]) -> Optional[int]:
    if not value:
        return None
    digits = "".join(ch for ch in value if ch.isdigit())
    return int(digits) if digits else None


def _build_payload(entry: PipelineEntry) -> Dict[str, Any]:
    payload: Dict[str, Any] = {
        "name": entry.programName or entry.projectCode or "QuoteHub Project",
        "notes": f"Generated by QuoteHub integration. Project code: {entry.projectCode or 'n/a'}.",
        "active": 1,
    }

    start_date = _to_date_only(entry.startDate)
    end_date = _to_date_only(entry.endDate)

    # Push system project code into Float's project_code for traceability
    if entry.projectCode:
        payload["project_code"] = entry.projectCode

    # Derive client_id and project_stage_id from system project data (digits only)
    numeric_code = _extract_digits(entry.projectCode)
    if numeric_code is not None:
        payload["client_id"] = numeric_code
        payload["project_stage_id"] = numeric_code
    if start_date:
        payload["start_date"] = start_date
    if end_date:
        payload["end_date"] = end_date

    return payload


async def create_float_project(entry: PipelineEntry) -> Optional[Dict[str, Any]]:
    """
    Create a project in Float for the given pipeline entry.
    Any errors are logged and swallowed so we don't block pipeline creation.
    """
    api_key = settings.float_api_key
    if not api_key:
        log.info("Float API key not configured; skipping Float project creation for %s", entry.projectCode)
        return None

    payload = _build_payload(entry)
    url = f"{settings.float_base_url.rstrip('/')}/projects"
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
    }

    try:
        async with httpx.AsyncClient(timeout=httpx.Timeout(15.0, read=20.0)) as client:
            response = await client.post(url, headers=headers, json=payload)

        if response.is_success:
            body = response.json()
            log.info("Created Float project for %s: %s", entry.projectCode, body.get("name") or payload["name"])
            return body

        log.warning(
            "Float project creation failed for %s (status %s): %s",
            entry.projectCode,
            response.status_code,
            response.text,
        )
    except Exception:
        log.exception("Error creating Float project for %s", entry.projectCode)

    return None
