from typing import Dict, List

CLIENT_LIST: List[str] = [
    "ABI",
    "Adidas CAN",
    "Adidas USA",
    "Bell",
    "Coca-Cola Canada",
    "Coca-Cola USA",
    "Ethos",
    "Flora Foods",
    "Hershey",
    "Holman",
    "Kraft CAN",
    "Kraft USA",
    "Labatt",
    "Luxe",
    "Mars",
    "McCain",
    "Mercedes Benz",
    "Microsoft CAN",
    "Microsoft USA",
    "NBD - Canada",
    "NBD - US",
    "Other - Canada",
    "Other - US",
    "Pointsbet",
    "RBC",
    "Rona",
    "Sephora",
    "Shopify",
    "The Kitchen",
    "Toyota",
    "Unilever",
]

CLIENT_RATE_CARD_MAP: Dict[str, str] = {
    "Labatt": "Labatt",
    "RBC": "RBC",
    "Toyota": "Toyota Retainer",
    "Hershey": "Hershey Retainer",
    "Coca-Cola Canada": "ABI",
    "Coca-Cola USA": "ABI",
    "Bell": "Rogers",
    "Mars": "ABI",
    "Kraft CAN": "ABI",
    "Kraft USA": "ABI",
    "McCain": "Standard",
    "Microsoft CAN": "Standard",
    "Microsoft USA": "Standard",
    "Shopify": "Standard",
    "Sephora": "Standard",
    "Unilever": "Standard",
    "Adidas CAN": "Standard",
    "Adidas USA": "Standard",
}

CLIENT_CATEGORY_MAP: Dict[str, str] = {
    "Adidas CAN": "Category 3 - Prospective Growth",
    "Adidas USA": "Category 3 - Prospective Growth",
    "Bell": "Category 5 - Baseline Booster",
    "Coca-Cola Canada": "Category 1 - Foundational",
    "Coca-Cola USA": "Category 1 - Foundational",
    "Ethos": "Category 5 - Baseline Booster",
    "Flora Foods": "Category 5 - Baseline Booster",
    "Hershey": "Category 3 - Prospective Growth",
    "Holman": "Category 4 - Service Anchors",
    "Kraft CAN": "Category 1 - Foundational",
    "Kraft USA": "Category 1 - Foundational",
    "Labatt": "Category 1 - Foundational",
    "Luxe": "Category 3 - Prospective Growth",
    "Mars": "Category 3 - Prospective Growth",
    "McCain": "Category 2 - Core Partners",
    "Mercedes Benz": "Category 5 - Baseline Booster",
    "Microsoft CAN": "Category 2 - Core Partners",
    "Microsoft USA": "Category 2 - Core Partners",
    "NBD - Canada": "Category 5 - Baseline Booster",
    "NBD - US": "Category 5 - Baseline Booster",
    "Other - Canada": "Category 5 - Baseline Booster",
    "Other - US": "Category 5 - Baseline Booster",
    "Pointsbet": "Category 2 - Core Partners",
    "RBC": "Category 1 - Foundational",
    "Rona": "Category 4 - Service Anchors",
    "Sephora": "Category 2 - Core Partners",
    "Shopify": "Category 2 - Core Partners",
    "The Kitchen": "Category 4 - Service Anchors",
    "Toyota": "Category 2 - Core Partners",
    "Unilever": "Category 3 - Prospective Growth",
}


def get_pipeline_metadata():
    return {
        "clients": CLIENT_LIST,
        "rateCardMap": CLIENT_RATE_CARD_MAP,
        "clientCategoryMap": CLIENT_CATEGORY_MAP,
    }
